version: "3.9"

services:

  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    platform: linux/arm64

    hostname: spark-master

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master

    ports:
      - "7077:7077"
      - "8080:8080"

    networks:
      - spark-net


  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    platform: linux/arm64

    hostname: spark-worker

    depends_on:
      - spark-master

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077

    environment:
      SPARK_WORKER_MEMORY: 4G
      SPARK_WORKER_CORES: 4

    networks:
      - spark-net


  jupyter:
    build: .
    container_name: jupyter
    platform: linux/arm64

    depends_on:
      - spark-master
      - spark-worker

    ports:
      - "8888:8888"
      - "4040:4040"

    environment:
      JUPYTER_ENABLE_LAB: "yes"

    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./include:/home/jovyan/include

    command:
      - start-notebook.sh
      - --NotebookApp.token=
      - --NotebookApp.password=

    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge